#ifndef WCU_FIRMWARE_CONFIG_H
#define WCU_FIRMWARE_CONFIG_H

#define WCU_FIRMWARE_REV_MAJOR 1
#define WCU_FIRMWARE_REV_MINOR 2

//#define LOCATION_PROVIDER_ONBOARD_GPS
//#define DATETIME_PROVIDER_ONBOARD_GPS

// Disable barometer, PCB footprint incorrect
//#define BAROMETER_DISABLED 1
#define EXTERNAL_TEMP_DISABLED 1


#endif // WCU_FIRMWARE_CONFIG_H
