#include "comms/bluetooth.h"

#include "HAL_BT.h"

/* 
 * This include is autogenerated by BTStack, it contains macros for the custom
 * GATT service characteristics (by their UUIDs).
 *
 * @see smartwindshield-bt.gatt
 */
#include "smartwindshield-bt.h"

#include <stdint.h>

// From smartwindshield-bt.h
extern const uint8_t profile_data[];

static const char* DEVICE_NAME = "SmartWindshield";

// Constants for Characteristic IDs and sizes

static const uint16_t CHARACTERISTIC_DRIVER_HEIGHT = ATT_CHARACTERISTIC_90E4BA9D_227F_41A6_8D10_6D8187F4A770_01_VALUE_HANDLE;
static const uint16_t CHARACTERISTIC_WINDSHIELD_LENGTH = ATT_CHARACTERISTIC_B98EF484_35F0_4DE5_BC1D_8F54C5733855_01_VALUE_HANDLE;
static const uint16_t CHARACTERISTIC_WINDSHIELD_HEIGHT = ATT_CHARACTERISTIC_CAE35C83_85EA_450F_9CD5_60FC4C3F2867_01_VALUE_HANDLE;
static const size_t CHARACTERISTIC_SIZE_DRIVER_HEIGHT = sizeof(uint16_t);
static const size_t CHARACTERISTIC_SIZE_WINDSHIELD_LENGTH = sizeof(uint16_t);
static const size_t CHARACTERISTIC_SIZE_WINDSHIELD_HEIGHT = sizeof(uint16_t);

void BluetoothComms_Init(void) {
    HAL_BT_Init(DEVICE_NAME, profile_data);

    HAL_BT_RegisterCharacteristic(CHARACTERISTIC_DRIVER_HEIGHT,
                                  CHARACTERISTIC_SIZE_DRIVER_HEIGHT);
    HAL_BT_RegisterCharacteristic(CHARACTERISTIC_WINDSHIELD_LENGTH,
                                  CHARACTERISTIC_SIZE_WINDSHIELD_LENGTH);
    HAL_BT_RegisterCharacteristic(CHARACTERISTIC_WINDSHIELD_HEIGHT,
                                  CHARACTERISTIC_SIZE_WINDSHIELD_HEIGHT);
}
